<?php

/**
 * @file
 * islandora_newspaper_landing_page.install
 * Installs the required object to piggy back the newspaper solution pack.
 */

/**
 * Implements hook_requirements().
 */
function islandora_newspaper_landing_page_requirements($phase) {
}

/**
 * Implements hook_install().
 *
 * @see islandora_islandora_required_objects()
 */
function islandora_newspaper_landing_page_install() {
}

/**
 * Implements hook_uninstall().
 */
function islandora_newspaper_landing_page_uninstall() {
  $variables = array(
    'islandora_newspaper_landing_page_ancestors_field',
    'islandora_newspaper_landing_page_sort_field',
    'islandora_newspaper_landing_page_sort_order',
  );
  array_map('variable_del', $variables);
}